In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.DataFrame({ 'text': ['people watch campusx','campusx watch campusx','people write comment','campusx write comment'], 'output': [1,1,0,0]})

In [3]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
w = CountVectorizer()


In [11]:
# Fit and transform the text column
bow = w.fit_transform(df['text'])

In [12]:
# Print the vocabulary
print(w.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [14]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [15]:
w.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)